#!/usr/bin/env zsh
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# load custom executable functions
for function in ~/.dotfiles/zsh/functions/*; do
  source $function
done

export ZSH="/Users/grip/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
  aws
  brew
  docker
  docker-compose
  git
  gitfast
  kubectl
  vscode
  alias-tips
  fast-syntax-highlighting
  history-search-multi-word
  zsh-autosuggestions
)

# ssh-agent
#zstyle :omz:plugins:ssh-agent agent-forwarding on

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Init aws_completer
source ~/.dotfiles/zsh/aws_zsh_completer.sh
