#!/usr/bin/env zsh

eval "$(pyenv init --path)"
GITSTATUS_LOG_LEVEL=DEBUG

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# load custom executable functions
for function in ~/.dotfiles/zsh/functions/*; do
  source $function
done

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
  aws
  brew
  docker
  docker-compose
  git
  gitfast
  kubectl
  vscode
  alias-tips
  fast-syntax-highlighting
  zsh-autosuggestions
)

# ssh-agent
#zstyle :omz:plugins:ssh-agent agent-forwarding on


source $ZSH/oh-my-zsh.sh
source $ZSH/custom/plugins/history-search-multi-word/H-S-MW.plugin.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Init aws_completer
source ~/.dotfiles/zsh/aws_zsh_completer.sh

# Set the open file limit
ulimit -n unlimited
ulimit -f unlimited 


export NVM_DIR=~/.nvm
 [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
# The next line updates PATH for the Google Cloud SDK.
if [ -f '~/google-cloud-sdk/path.zsh.inc' ]; then . '~/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '~/google-cloud-sdk/completion.zsh.inc' ]; then . '~/google-cloud-sdk/completion.zsh.inc'; fi
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
#alias python=/usr/bin/python3


# pnpm
export PNPM_HOME="/Users/matti/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/matti/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions
